"""file model

Revision ID: 9e6e9553112f
Revises: 
Create Date: 2023-03-01 14:23:04.946890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6e9553112f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file__mime_type', sa.String(length=1015), nullable=True),
    sa.Column('file__ext', sa.String(length=1009), nullable=True),
    sa.Column('file__file_name', sa.String(length=1015), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
